- name: "create directory"
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    path: "{{ item }}"
  with_items:
    - "{{ grafana__dir_upload }}"

# - name: "yum: repofile"
#   template:
#     owner: root
#     group: root
#     mode: 0755
#     src: "{{ item.temp }}"
#     dest: "/etc/yum.repos.d/{{ item.repo }}"
#   with_items:
#     - "{{ grafana__yum_list }}"

# - name: "yum: install grafana"
#   yum:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - "{{ grafana__rpm_list }}"

- name: "grafana: copy file to target server"
  copy:
    owner: root
    group: root
    src: "{{ grafana__install_media }}"
    dest: "{{ grafana__install_media_uploaded }}"

- name: "grafana install rpm"
  shell: |
    rpm -ivh {{ grafana__install_media_uploaded }}
  ignore_errors: yes

- name: "grafana: config file"
  template:
    owner: root
    group: grafana
    mode: 0755
    src: "grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"

- name: "grafana-server: start linux service"
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  ignore_errors: yes
